server:
  port: 8383

dubbo:
  application:
    name: easyspringboot-dubbo-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
    timeout: 10000